import type { User, MedicationSearchResult } from '../types';

export const mockUsers: User[] = [
  {
    id: 'dr-emily-chen',
    name: 'Dr. Emily Chen',
    role: 'physician',
    specialty: 'Internal Medicine',
  },
];

export const mockMedications: MedicationSearchResult[] = [
  {
    id: 'amox-250',
    name: 'Amoxicillin 250mg capsule',
    strength: '250mg',
    form: 'capsule',
    commonDosing: ['250mg TID', '250mg BID'],
    isControlled: false,
  },
  {
    id: 'amox-500',
    name: 'Amoxicillin 500mg capsule',
    strength: '500mg',
    form: 'capsule',
    commonDosing: ['500mg TID', '500mg BID'],
    isControlled: false,
  },
  {
    id: 'amox-875',
    name: 'Amoxicillin 875mg tablet',
    strength: '875mg',
    form: 'tablet',
    commonDosing: ['875mg BID'],
    isControlled: false,
  },
  {
    id: 'lisinopril-5',
    name: 'Lisinopril 5mg tablet',
    strength: '5mg',
    form: 'tablet',
    commonDosing: ['5mg daily'],
    isControlled: false,
  },
  {
    id: 'lisinopril-10',
    name: 'Lisinopril 10mg tablet',
    strength: '10mg',
    form: 'tablet',
    commonDosing: ['10mg daily'],
    isControlled: false,
  },
  {
    id: 'lisinopril-20',
    name: 'Lisinopril 20mg tablet',
    strength: '20mg',
    form: 'tablet',
    commonDosing: ['20mg daily'],
    isControlled: false,
  },
  {
    id: 'metformin-500',
    name: 'Metformin 500mg tablet',
    strength: '500mg',
    form: 'tablet',
    commonDosing: ['500mg BID', '500mg daily'],
    isControlled: false,
  },
  {
    id: 'metformin-850',
    name: 'Metformin 850mg tablet',
    strength: '850mg',
    form: 'tablet',
    commonDosing: ['850mg BID'],
    isControlled: false,
  },
  {
    id: 'metformin-1000',
    name: 'Metformin 1000mg tablet',
    strength: '1000mg',
    form: 'tablet',
    commonDosing: ['1000mg BID'],
    isControlled: false,
  },
  {
    id: 'atorvastatin-10',
    name: 'Atorvastatin 10mg tablet',
    strength: '10mg',
    form: 'tablet',
    commonDosing: ['10mg daily at bedtime'],
    isControlled: false,
  },
  {
    id: 'atorvastatin-20',
    name: 'Atorvastatin 20mg tablet',
    strength: '20mg',
    form: 'tablet',
    commonDosing: ['20mg daily at bedtime'],
    isControlled: false,
  },
  {
    id: 'atorvastatin-40',
    name: 'Atorvastatin 40mg tablet',
    strength: '40mg',
    form: 'tablet',
    commonDosing: ['40mg daily at bedtime'],
    isControlled: false,
  },
  {
    id: 'omeprazole-20',
    name: 'Omeprazole 20mg capsule',
    strength: '20mg',
    form: 'capsule',
    commonDosing: ['20mg daily before breakfast'],
    isControlled: false,
  },
  {
    id: 'omeprazole-40',
    name: 'Omeprazole 40mg capsule',
    strength: '40mg',
    form: 'capsule',
    commonDosing: ['40mg daily before breakfast'],
    isControlled: false,
  },
  {
    id: 'amlodipine-5',
    name: 'Amlodipine 5mg tablet',
    strength: '5mg',
    form: 'tablet',
    commonDosing: ['5mg daily'],
    isControlled: false,
  },
  {
    id: 'amlodipine-10',
    name: 'Amlodipine 10mg tablet',
    strength: '10mg',
    form: 'tablet',
    commonDosing: ['10mg daily'],
    isControlled: false,
  },
  {
    id: 'hydrocodone-5-325',
    name: 'Hydrocodone/APAP 5/325mg tablet',
    strength: '5/325mg',
    form: 'tablet',
    commonDosing: ['1-2 tablets every 4-6 hours PRN'],
    isControlled: true,
  },
  {
    id: 'oxycodone-5',
    name: 'Oxycodone 5mg tablet',
    strength: '5mg',
    form: 'tablet',
    commonDosing: ['5mg every 4-6 hours PRN'],
    isControlled: true,
  },
  {
    id: 'gabapentin-100',
    name: 'Gabapentin 100mg capsule',
    strength: '100mg',
    form: 'capsule',
    commonDosing: ['100mg TID'],
    isControlled: false,
  },
  {
    id: 'gabapentin-300',
    name: 'Gabapentin 300mg capsule',
    strength: '300mg',
    form: 'capsule',
    commonDosing: ['300mg TID'],
    isControlled: false,
  },
  {
    id: 'prednisone-5',
    name: 'Prednisone 5mg tablet',
    strength: '5mg',
    form: 'tablet',
    commonDosing: ['5mg daily', 'Taper per instructions'],
    isControlled: false,
  },
  {
    id: 'prednisone-10',
    name: 'Prednisone 10mg tablet',
    strength: '10mg',
    form: 'tablet',
    commonDosing: ['10mg daily', 'Taper per instructions'],
    isControlled: false,
  },
  {
    id: 'azithromycin-250',
    name: 'Azithromycin 250mg tablet',
    strength: '250mg',
    form: 'tablet',
    commonDosing: ['500mg day 1, then 250mg days 2-5'],
    isControlled: false,
  },
  {
    id: 'ciprofloxacin-500',
    name: 'Ciprofloxacin 500mg tablet',
    strength: '500mg',
    form: 'tablet',
    commonDosing: ['500mg BID'],
    isControlled: false,
  },
  {
    id: 'albuterol-inhaler',
    name: 'Albuterol 90mcg inhaler',
    strength: '90mcg/actuation',
    form: 'inhaler',
    commonDosing: ['2 puffs every 4-6 hours PRN'],
    isControlled: false,
  },
];
